apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infra-template
  title: Terraform
  description: Template for creating infra using terraform
  annotations:
    github.com/project-slug: 'syngenta-digital/{{ requiredParam "name" }}'
  tags:
    - terraform
    - infra
spec:
  owner: shubham@syngenta.com
  type: Infra
  team: '{{ requiredParam "team_name" }}'
  parameters:
    - title: Fill in some steps
      required:
        - name
        - dev
        - qa
        - prod 
        - stage 
      properties:
        team_name:
          title: Team-name
          type: string
          description: Team of the Component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        name:
          title: Name
          type: string
          description: Unique name of the component
          
        dev:
          title: Dev
          type: string
          description: AWS Account No. of DEV
        
        qa:
          title: QA
          type: string
          description: AWS Account No. of QA
        
        prod:
          title: PROD
          type: string
          description: AWS Account No. of PROD
        stage:
          title: STAGE
          type: string
          description: AWS Account No. of STAGE( if don't have account just put 000000000000)
        
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: User
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          #default: github.com?owner=${{ requiredParam "owner" }}&repo=${{ requiredParam "name"}}
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - [{{ parameters.owner }}]
            # allowedRepos:
              # - [{{ parameters.name}}]
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          dev: ${{ parameters.dev }}
          qa: ${{ parameters.qa}}
          prod: ${{ parameters.prod }}
          stage: ${{ parameters.stage }}
          owner: ${{ parameters.owner }}
          team_name: ${{ parameters.team_name }}
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        # values:
        #   name: ${{ parameters.name }}
        #   dev: ${{ parameters.dev }}
        #   qa: ${{ parameters.qa}}
        #   prod: ${{ parameters.prod }}
        #   stage: ${{ parameters.stage }}
        #   owner: ${{ parameters.owner }}
        #   team_name: ${{ parameters.team_name }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
