# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0
  terraform: circleci/terraform@3.1

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - aws-cli/setup
      - checkout
      - terraform/init:
          path: .
      # - terraform/validate:
      #     path: .
      # - terraform/fmt:
      #     path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .
      # - terraform/destroy:
      #     path: .
    working_directory: ~/src
  workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
  